version: '3'

services:
  web:
    image: gcr.io/tymuj-4937c/tymuj-web:2.0.7
    build:
      context: .
    ports:
      - 80:80
    environment:
      PORT: 80
      FALLBACK_URI: https://109.205.73.82
      FALLBACK_HOST: tymuj.cz
